[Dataset](https://www.kaggle.com/datasets/bytadit/ecommerce-order-dataset/data)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df_orders = pd.read_csv('df_Orders.csv')
df_orderitems = pd.read_csv('df_OrderItems.csv')
df_customer = pd.read_csv('df_Customers.csv')
df_products = pd.read_csv('df_Products.csv')
df_payments = pd.read_csv('df_Payments.csv')

### Проверка Orders

In [5]:
df_orders.shape

(89316, 7)

In [7]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18

In [8]:
df_orders.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
89311,zlcLnXGgAabl,bfJtzkBGksdY,delivered,2018-08-19 17:25:36,2018-08-21 04:35:30,2018-08-30 14:47:46,2018-09-04
89312,IlTAoIkILwrq,4hjsCpj6FC7g,delivered,2017-12-15 11:20:27,2017-12-16 02:37:32,2017-12-20 19:23:40,2018-01-04
89313,uA6oXfftGVmT,DLn56oKHl9bv,delivered,2018-07-24 06:39:14,2018-07-24 11:20:39,2018-07-27 01:41:40,2018-08-01
89314,v3QtU6xlGDJp,auSfRYUQUOIq,delivered,2018-08-11 08:04:22,2018-08-11 08:24:40,2018-08-14 21:43:51,2018-08-17
89315,Xo1fqyXOC6CR,rhevVNXYJnEs,delivered,2018-06-09 21:46:58,2018-06-09 22:19:00,2018-06-14 15:03:46,2018-07-05

In [9]:
df_orders.sample(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
83228,6AHNlhtEaxW2,7LWf0iN4M1Lk,delivered,2017-09-15 00:36:44,2017-09-15 00:50:11,2017-09-26 18:26:51,2017-10-16
29777,y1nnitNpmi94,xRiTiWA3Iuy4,delivered,2018-07-21 22:35:28,2018-07-26 23:32:14,2018-08-02 21:18:40,2018-08-10
26707,y3qkMdv5rffg,uYCVz4FcQWhV,delivered,2018-02-19 15:33:55,2018-02-19 16:35:26,2018-03-05 20:34:32,2018-03-19
63790,r5uaYNraWYyq,m0oWSXUZreew,delivered,2017-02-25 09:21:20,2017-02-25 09:30:11,2017-03-08 12:59:03,2017-03-23
38612,Px1NoNWnwkXF,8cKCscw9Tyvx,delivered,2018-05-02 21:09:08,2018-05-02 21:35:30,2018-05-08 19:18:48,2018-05-25
26718,AKPwqeOiAp2H,oa9XcbQNa8vL,delivered,2018-05-22 21:06:32,2018-05-22 21:18:33,2018-05-28 19:12:57,2018-06-07
82614,xPP9uYn5dKKF,z79Mg8d6UXW3,delivered,2017-09-24 19:21:57,2017-09-24 19:30:23,2017-10-03 18:15:59,2017-10-19
10528,uMMCeUU9oNYT,8SYPafpSOcXG,delivered,2018-03-25 17:23:39,2018-03-25 17:35:24,2018-04-17 18:07:55,2018-04-20
56999,J3daQq4kW3CW,ZaiqhSnBHJkv,delivered,2018-03-05 10:51:31,2018-03-05 11:15:39,2018-03-10 00:52:20,2018-03-23
46738,CumWnyt1w536,JMWa7IYGqgV4,delivered,2018-08-08 14:40:51,2018-08-08 14:50:19,2018-08-15 17:46:51,2018-08-22