[Dataset](https://www.kaggle.com/datasets/bytadit/ecommerce-order-dataset/data)

In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
df_customer = pd.read_csv('df_Customers.csv')
df_orderitems = pd.read_csv('df_OrderItems.csv')
df_orders = pd.read_csv('df_Orders.csv')
df_payments = pd.read_csv('df_Payments.csv')
df_products = pd.read_csv('df_Products.csv')

In [32]:
df_customer.shape

(89316, 4)

In [33]:
df_customer.head()

    customer_id  customer_zip_code_prefix       customer_city customer_state
0  hCT0x9JiGXBQ                     58125     varzea paulista             SP
1  PxA7fv9spyhx                      3112  armacao dos buzios             RJ
2  g3nXeJkGI0Qw                      4119             jandira             SP
3  EOEsCQ6QlpIg                     18212          uberlandia             MG
4  mVz5LO2Vd6cL                     88868            ilhabela             SP

In [34]:
df_customer.tail()

        customer_id  customer_zip_code_prefix customer_city customer_state
89311  bfJtzkBGksdY                     94060        amparo             SP
89312  4hjsCpj6FC7g                     99835       itapevi             SP
89313  DLn56oKHl9bv                      2540     sao paulo             SP
89314  auSfRYUQUOIq                     12288      paulinia             SP
89315  rhevVNXYJnEs                     93048      brasilia             DF

In [35]:
df_customer.sample(10)

        customer_id  customer_zip_code_prefix     customer_city customer_state
24682  SZr7ipKNwg94                     37131          campinas             SP
70135  VnvjY1poUdYP                     26440    rio de janeiro             RJ
14994  cu26dgtqL4Y8                     88320         sao paulo             SP
43001  kGYmyGiA1Bdx                      4840          salvador             BA
23295  OEfiQXu4wTZT                     30820  perpetuo socorro             MG
88102  A2iFC9To9yat                      9636          umuarama             PR
16306  lCx26ErlNP6W                      3617          brasilia             DF
57914  Eu0fXJF5G7pJ                     88704           niteroi             RJ
67059  9tFgBAAwmJps                     38071        votorantim             SP
50418  8snZm3CGiksz                     87203         rio claro             SP

In [36]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.7 MB

In [37]:
df_customer['customer_zip_code_prefix'] = df_customer['customer_zip_code_prefix'].astype('str')

In [38]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  str
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: str(4)
memory usage: 2.7 MB

In [39]:
df_customer.columns

Index(['customer_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state'],
      dtype='str')

In [40]:
df_customer.isnull().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [46]:
df_customer.isna().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [43]:
df_customer.nunique()

customer_id                 89316
customer_zip_code_prefix    13930
customer_city                3735
customer_state                 27
dtype: int64

In [47]:
df_customer.duplicated().sum()

np.int64(0)

In [50]:
df_customer.duplicated('customer_id').sum()

np.int64(0)

In [53]:
df_orderitems.shape

(89316, 5)

In [54]:
df_orderitems.head()

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [55]:
df_orderitems.tail()

           order_id    product_id     seller_id    price  shipping_charges
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

In [56]:
df_orderitems.sample(10)

           order_id    product_id     seller_id    price  shipping_charges
52763  FTxXzQY0iSfd  go1LvvX697Si  8mVLKV0XOTsx   126.69             12.63
504    QsnXzn81euhJ  anvtFHva439b  T7OJcZtdnwO5   150.82             65.05
2732   PfZiwkiTFrNg  xX35smKe93PM  ISS9Wr4Lvyi0    18.04             21.83
1124   6LB4Nh0KeiKW  vq3euGOVCtVd  XePbD5Ocm6Yk   274.95             10.78
38470  9bTbFqsvg6Qg  1G4Huh4n4Qju  ROvrtSKN89oc    89.57             32.34
84443  ntpC3GkzqKkW  5RbcHQdSdXZY  xbr8ZnHWrWgb  3089.00             20.81
89145  V9Fn67YTbCI6  f6yyPpIHqpid  yGbPyLPc8PmT   111.27             32.34
39051  lTHyizidkkBQ  SLANLZkCbYI1  Mhg6gqpiKkO7    42.89             47.55
49912  IaRG5Ap9llpq  alDXaj66Q8F8  CutJkKSkib8L   104.36             47.55
75629  sijsk3IFr8fa  9hsRgO81MHGS  VEpUiS8q8p8X    35.94             38.97

In [57]:
df_orderitems.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  str
 1   product_id        89316 non-null  str
 2   seller_id         89316 non-null  str
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), str(3)
memory usage: 3.4 MB

In [58]:
df_orderitems.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges'], dtype='str')

In [59]:
df_orderitems.isnull().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [60]:
df_orderitems.isna().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [62]:
df_orderitems.nunique()

order_id            89316
product_id          27451
seller_id            2929
price                5235
shipping_charges     6327
dtype: int64

In [68]:
df_orderitems.describe()

              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000

In [63]:
df_orderitems.duplicated().sum()

np.int64(0)