[Паспорт таблицы](./EDA_orderitems_passport.md)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Проверка OrderItems

#### План проверки
* Проверить уникальность пары (order_id,order_item_id).
* Посчитать количество позиций в заказе, распределение (1‑позиционные / многопозиционные заказы).
* Проверить пропуски и нули в price и shipping_charges.
* Найти аномально большие/малые цены и стоимости доставки (boxplot‑подход, quantiles).
* Посчитать сумму price + shipping_charges по order_id и сравнить с суммой оплат (через Payments).
* Проверить, все ли order_id из Order Items присутствуют в Orders.
* Проверить, все ли product_id присутствуют в Products.
* Посчитать средний чек заказа и распределение (sum по order_id).
* Посчитать долю позиций с нулевой доставкой, посмотреть по категориям товаров.
* Проверить, есть ли позиции с отрицательной ценой/доставкой (возвраты, ошибки).

In [2]:
df_orderitems = pd.read_csv('df_OrderItems.csv')

In [4]:
df_orderitems.shape

(89316, 5)

In [5]:
df_orderitems.head()

       order_id    product_id     seller_id   price  shipping_charges
0  Axfy13Hk4PIk  90K0C1fIyQUf  ZWM05J9LcBSF  223.51             84.65
1  v6px92oS8cLG  qejhpMGGVcsl  IjlpYfhUbRQs  170.80             23.79
2  Ulpf9skrhjfm  qUS5d2pEAyxJ  77p2EYxcM9MD   64.40             17.38
3  bwJVWupf2keN  639iGvMyv0De  jWzS0ayv9TGf  264.50             30.72
4  Dd0QnrMk9Cj5  1lycYGcsic2F  l1pYW6GBnPMr  779.90             30.66

In [6]:
df_orderitems.tail()

           order_id    product_id     seller_id    price  shipping_charges
89311  zlcLnXGgAabl  W8vikEizUggJ  2QjevWskirjm    31.99            188.65
89312  IlTAoIkILwrq  KXSbyJWtMMwZ  BFS9XJPapWv0   282.00              1.64
89313  uA6oXfftGVmT  EG4wDSpFyTth  TuPm19CMKvrM    58.10              4.09
89314  v3QtU6xlGDJp  ZWyg4uNWPHjJ  yGbPyLPc8PmT  2899.00            113.01
89315  Xo1fqyXOC6CR  5pbzE0rDy61l  mkWN70fui2ro    37.88             70.06

In [7]:
df_orderitems.sample(10)

           order_id    product_id     seller_id   price  shipping_charges
85413  52M9uBp0yeZs  QqRt9fpBjLde  V8Stg8HdXCTe  509.99             31.00
19268  f1UMWWXxOuig  50ZMqeoBugxr  i2VPd2aaDnzs   95.03             43.40
3839   1SoNUPO4JExo  mUznAqpaIzIf  y2wUonMtvOnt   82.59            105.32
16575  SgST1ENpwhe4  LxzieVzc0fZH  Djfhy4pnkKOC  213.00             32.62
23310  FQ7v41D8VaYC  QWaws5EnTx6p  Xuc12twC4Fsy   42.89             20.90
45446  rphn24dvNvlW  jrc0v3ZRw6Zg  ZNVgXvCvMqkS  266.55             38.66
50139  q5AldvARpWXG  TVOsff9OyoK2  K0qPVGdA91KO  178.00             12.92
60130  PnTZfcNQ1LQK  sB3mH3n4QEcI  hmS6KkvxMbyF  109.60             37.81
12240  3Km6sbzTYzLP  Moxje1YcUngK  ebluER1nIuqZ  238.40            121.73
34465  XA187dxSG9Lm  nSGtbv1lwtBP  wwkEiuOOSSP1  313.90             29.07

In [8]:
df_orderitems.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'shipping_charges'], dtype='str')

In [10]:
df_orderitems.info()

<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  str
 1   product_id        89316 non-null  str
 2   seller_id         89316 non-null  str
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), str(3)
memory usage: 3.4 MB

In [11]:
df_orderitems.isnull().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [13]:
df_orderitems.isna().sum()

order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

In [16]:
df_orderitems.nunique()

order_id            89316
product_id          27451
seller_id            2929
price                5235
shipping_charges     6327
dtype: int64

In [22]:
df_orderitems.duplicated().sum()

np.int64(0)

KeyError: ('order_id ', 'product_id ')